'use strict';

// Writes the public pages from the published records, and nothing else:
//   observations.html        the sequence and its extent, between GENERATED markers
//   observations/<number>/index.html   each Observation on its own sheet
//   sitemap.xml              the sheet addresses, between GENERATED markers
// The output depends only on the repository's files, so building twice gives the
// same bytes. Records, text, and images are only read.

const fs = require('node:fs');
const path = require('node:path');
const records = require('./records');
const render = require('./render');

const INDEX_FILE = 'observations.html';
const SITEMAP_FILE = 'sitemap.xml';
const GENERATED_MARK = 'Generated by `npm run observations:build`';

function region(name) {
  return {
    begin: `<!-- BEGIN GENERATED: ${name} (npm run observations:build) -->`,
    end: `<!-- END GENERATED: ${name} -->`,
  };
}

function replaceRegion(text, name, inner, file) {
  const { begin, end } = region(name);
  const a = text.indexOf(begin);
  const b = text.indexOf(end);
  if (a < 0 || b < a || text.indexOf(begin, a + 1) >= 0) {
    throw new Error(`${file} must hold exactly one "${name}" region:\n  ${begin}\n  ${end}`);
  }
  // The inner lines are never indented: a contributor's paragraph keeps its own
  // line breaks and spacing (pre-wrap), so added whitespace would show.
  const indent = /[ \t]*$/.exec(text.slice(0, a))[0];
  const body = inner ? `\n${inner}\n${indent}` : `\n${indent}`;
  return text.slice(0, a + begin.length) + body + text.slice(b);
}

// Renders everything and returns [{ file, content | null }], where null means the
// file should not exist. `extra` adds records that are not published (the
// preview), and `robots` marks every sheet (the preview is noindex).
function plan(root, { extra = [], robots = null, now } = {}) {
  const published = records.publishedInOrder(root, { now });
  const items = records.sortRecords([...published, ...extra]);
  const indexPath = path.join(root, INDEX_FILE);
  const indexHtml = fs.readFileSync(indexPath, 'utf8');
  const chrome = render.extractChrome(indexHtml);

  let index = replaceRegion(indexHtml, 'observations-extent', render.renderExtent(items), INDEX_FILE);
  index = replaceRegion(index, 'observations-sequence', render.renderSequence(items), INDEX_FILE);

  const out = [{ file: INDEX_FILE, content: index }];
  items.forEach((item, i) => {
    out.push({
      file: path.join(path.relative(root, item.dir), records.GENERATED_FILE),
      content: render.renderSheetPage(item, { prev: items[i - 1], next: items[i + 1], chrome, robots }),
    });
  });

  const sitemapPath = path.join(root, SITEMAP_FILE);
  if (fs.existsSync(sitemapPath)) {
    const urls = published.length
      ? records.sortRecords(published).map((it) => `<url><loc>${render.SITE}${render.url(it.number)}</loc></url>`).join('\n')
      : '';
    out.push({ file: SITEMAP_FILE, content: replaceRegion(fs.readFileSync(sitemapPath, 'utf8'), 'observations', urls, SITEMAP_FILE) });
  }

  // A generated sheet left in a directory that no longer holds a published
  // record (for example after a directory was moved by hand) is removed.
  const pubDir = records.dirs(root).published;
  if (fs.existsSync(pubDir)) {
    for (const e of fs.readdirSync(pubDir, { withFileTypes: true })) {
      if (!e.isDirectory() || e.name.startsWith('_') || e.name.startsWith('.')) continue;
      const page = path.join(pubDir, e.name, records.GENERATED_FILE);
      const rel = path.relative(root, page);
      if (out.some((o) => o.file === rel) || !fs.existsSync(page)) continue;
      if (fs.readFileSync(page, 'utf8').includes(GENERATED_MARK)) out.push({ file: rel, content: null });
    }
  }
  return { items, published, files: out };
}

// Writes what differs. With `check`, writes nothing and reports what would change.
function build(root, { check = false, now } = {}) {
  const { published, files } = plan(root, { now });
  const changed = [];
  for (const { file, content } of files) {
    const abs = path.join(root, file);
    const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
    if (current === content) continue;
    changed.push(file);
    if (check) continue;
    if (content === null) fs.rmSync(abs);
    else fs.writeFileSync(abs, content);
  }
  return { published: published.length, changed };
}

module.exports = { INDEX_FILE, SITEMAP_FILE, GENERATED_MARK, region, replaceRegion, plan, build };
