'use strict';

// The source of an Observation and the rules it must satisfy before it can be
// previewed or published.
//
//   observations/_drafts/<slug>/     a draft: ignored by git and by Vercel
//   observations/<slug>/             published: committed and deployed
//     observation.json               the record (never deployed)
//     body.txt | body.md             the contributor's text, byte for byte (never deployed);
//     body-2.md …                    a later text block, when text and images alternate
//     images/<slug>-<n>.<ext>        the contributor's images (deployed)
//
// The material is `blocks`, an ordered list. Each block is a text file
// ({ "text": "body.txt" }) or an image ({ "image": "images/…", "alt": "…",
// "caption"?: "…" }). The page shows the blocks in exactly this order;
// consecutive images share one row.
//     index.html                     generated by the build; never edited by hand
//
// A record's location and its `status` must agree. Nothing in this file writes.

const fs = require('node:fs');
const path = require('node:path');
const { SUPPORTED, probeImage } = require('./images');

const PUBLISHED_DIR = 'observations';
const DRAFTS_DIR = path.join('observations', '_drafts');
const RECORD_FILE = 'observation.json';
const GENERATED_FILE = 'index.html';

const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SLUG_MAX = 80;
const KEYS = ['slug', 'status', 'published_at', 'title', 'author', 'author_role', 'context', 'blocks'];
const TEXT_KEYS = ['text'];
const IMAGE_KEYS = ['image', 'alt', 'caption'];
const TEXT_EXTENSIONS = ['.txt', '.md'];
const TEXT_NAME = /^body(?:-[2-9]|-[1-9]\d+)?\.(?:txt|md)$/;
const IMAGE_EXTENSIONS = Object.values(SUPPORTED).flat();

// Limits follow the submission form (api/observations.js) where it has one.
const LIMITS = { title: 200, author: 120, author_role: 80, context: 160, alt: 1000, caption: 600, body: 40_000 };
const IMAGE_WARN_BYTES = 3_000_000;
const IMAGE_MAX_BYTES = 10_000_000;
const IMAGE_MAX = 24;
const BLOCK_MAX = 60;

// A date (YYYY-MM-DD) or a UTC instant (YYYY-MM-DDTHH:MM[:SS]Z). The instant
// orders several Observations published on the same day.
const DATE = /^(\d{4})-(\d{2})-(\d{2})(?:T(\d{2}):(\d{2})(?::(\d{2}))?Z)?$/;

function parsePublishedAt(value) {
  if (typeof value !== 'string') return null;
  const m = DATE.exec(value);
  if (!m) return null;
  const [, y, mo, d, h = '00', mi = '00', s = '00'] = m;
  const t = Date.UTC(+y, +mo - 1, +d, +h, +mi, +s);
  const back = new Date(t);
  if (back.getUTCFullYear() !== +y || back.getUTCMonth() !== +mo - 1 || back.getUTCDate() !== +d) return null;
  if (+h > 23 || +mi > 59 || +s > 59 || +y < 2000) return null;
  return t;
}

function isSlug(slug) {
  return typeof slug === 'string' && slug.length <= SLUG_MAX && SLUG.test(slug);
}

function dirs(root) {
  return { published: path.join(root, PUBLISHED_DIR), drafts: path.join(root, DRAFTS_DIR) };
}

function listSlugs(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.'))
    .map((e) => e.name)
    .sort();
}

// Where a slug lives now: 'published', 'draft', 'both', or null.
function locate(root, slug) {
  const d = dirs(root);
  const pub = fs.existsSync(path.join(d.published, slug));
  const draft = fs.existsSync(path.join(d.drafts, slug));
  if (pub && draft) return 'both';
  return pub ? 'published' : draft ? 'draft' : null;
}

function recordDir(root, slug, where) {
  const d = dirs(root);
  return path.join(where === 'published' ? d.published : d.drafts, slug);
}

// A path named inside a record must stay inside that record's directory: relative,
// forward slashes, no dot segments, no symbolic links anywhere along it.
function safeRelative(dir, rel) {
  if (typeof rel !== 'string' || !rel) return 'is empty';
  if (rel.includes('\\') || rel.includes('\0')) return 'contains a backslash or a NUL';
  if (path.posix.isAbsolute(rel) || /^[a-zA-Z]:/.test(rel)) return 'is absolute';
  const parts = rel.split('/');
  if (parts.some((p) => p === '' || p === '.' || p === '..' || p.startsWith('.'))) return 'has an empty, dot, or parent segment';
  if (!/^[A-Za-z0-9._\/-]+$/.test(rel)) return 'may only use letters, digits, ".", "_", "-" and "/"';
  let at = dir;
  for (const p of parts) {
    at = path.join(at, p);
    let st;
    try { st = fs.lstatSync(at); } catch { return 'does not exist'; }
    if (st.isSymbolicLink()) return 'is or passes through a symbolic link';
  }
  if (!fs.statSync(at).isFile()) return 'is not a file';
  return null;
}

function readText(file) {
  const buf = fs.readFileSync(file);
  let text;
  try { text = new TextDecoder('utf-8', { fatal: true }).decode(buf); } catch { return { error: 'is not valid UTF-8' }; }
  if (text.includes('\0')) return { error: 'contains a NUL character' };
  return { text: text.replace(/^﻿/, '') };
}

function checkLine(errors, record, key, { required = false } = {}) {
  const v = record[key];
  if (v === undefined || v === null) {
    if (required) errors.push(`${key} is required`);
    return;
  }
  if (typeof v !== 'string') return errors.push(`${key} must be text`);
  if (!v.trim()) return errors.push(`${key} is empty; remove the field instead`);
  if (v !== v.trim()) errors.push(`${key} has leading or trailing spaces`);
  if (/[\r\n]/.test(v)) errors.push(`${key} must be a single line`);
  if (LIMITS[key] && [...v].length > LIMITS[key]) errors.push(`${key} is longer than ${LIMITS[key]} characters`);
}

const EMAIL_LIKE = /[^\s@<>()]+@[^\s@<>()]+\.[a-z]{2,}/i;
const REFERENCE_LIKE = /\bO–[A-Z0-9]{4,}/;

// Loads one record and checks it. Returns
//   { slug, where, dir, record, blocks, images, texts, errors, warnings }
// where blocks is the material in order:
//   { type: 'text', file, kind: 'txt' | 'md', text }
//   { type: 'image', file, alt, caption, width, height, format, bytes }
// and images and texts are the same blocks by type.
// `where` is the location it was read from; `expect` is the status that location requires.
function inspect(root, slug, where, { now = Date.now() } = {}) {
  const errors = [];
  const warnings = [];
  const dir = recordDir(root, slug, where);
  const result = { slug, where, dir, record: null, blocks: [], images: [], texts: [], errors, warnings };

  if (!isSlug(slug)) errors.push(`the directory name "${slug}" is not a valid slug (lowercase letters, digits, single hyphens, at most ${SLUG_MAX})`);
  const dirStat = fs.existsSync(dir) ? fs.lstatSync(dir) : null;
  if (!dirStat) { errors.push(`${path.relative(root, dir)} does not exist`); return result; }
  if (dirStat.isSymbolicLink() || !dirStat.isDirectory()) { errors.push(`${path.relative(root, dir)} is not a plain directory`); return result; }

  const recordPath = path.join(dir, RECORD_FILE);
  if (!fs.existsSync(recordPath)) { errors.push(`${RECORD_FILE} is missing`); return result; }
  let record;
  try { record = JSON.parse(fs.readFileSync(recordPath, 'utf8')); } catch (err) {
    errors.push(`${RECORD_FILE} is not valid JSON (${err.message})`);
    return result;
  }
  if (!record || typeof record !== 'object' || Array.isArray(record)) { errors.push(`${RECORD_FILE} must hold one object`); return result; }
  result.record = record;

  for (const key of Object.keys(record)) if (!KEYS.includes(key)) errors.push(`unknown field "${key}"`);

  // Identity and status.
  if (record.slug !== slug) errors.push(`slug "${record.slug}" does not match its directory "${slug}"`);
  const expected = where === 'published' ? 'published' : 'draft';
  if (record.status !== 'draft' && record.status !== 'published') errors.push('status must be "draft" or "published"');
  else if (record.status !== expected) {
    errors.push(where === 'published'
      ? `status is "${record.status}" but the record is in ${PUBLISHED_DIR}/; use observation:unpublish to withdraw it`
      : `status is "${record.status}" but the record is in ${DRAFTS_DIR}/; use observation:publish to publish it`);
  }
  if (record.published_at !== undefined && record.published_at !== null) {
    const t = parsePublishedAt(record.published_at);
    if (t === null) errors.push(`published_at "${record.published_at}" is not a valid date (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ)`);
    else if (t > now + 36 * 3600 * 1000) errors.push(`published_at ${record.published_at} is in the future`);
    if (expected === 'draft') errors.push('a draft has no published_at; it is set by observation:publish');
  } else if (expected === 'published') {
    errors.push('published_at is required for a published Observation');
  }

  // Attribution and framing.
  for (const key of ['title', 'author', 'author_role', 'context']) checkLine(errors, record, key);
  if (record.author_role != null && record.author == null) errors.push('author_role needs an author; an unsigned Observation has no role');

  // The material, in order.
  const seen = new Set();
  if (record.blocks === undefined) errors.push('blocks is required: the text and images, in the order they are read');
  else if (!Array.isArray(record.blocks)) errors.push('blocks must be a list');
  else {
    if (!record.blocks.length) errors.push('an Observation needs at least one text or image block');
    if (record.blocks.length > BLOCK_MAX) errors.push(`at most ${BLOCK_MAX} blocks`);
    const imageCount = record.blocks.filter((b) => b && typeof b === 'object' && 'image' in b).length;
    if (imageCount > IMAGE_MAX) errors.push(`at most ${IMAGE_MAX} images`);
    let lastWasText = false;
    record.blocks.forEach((block, i) => {
      const label = `block ${i + 1}`;
      if (!block || typeof block !== 'object' || Array.isArray(block)) return errors.push(`${label} must be an object`);
      const isText = 'text' in block, isImage = 'image' in block;
      if (isText === isImage) return errors.push(`${label} must have exactly one of "text" (a .txt or .md file) or "image"`);
      for (const key of Object.keys(block)) if (!(isText ? TEXT_KEYS : IMAGE_KEYS).includes(key)) errors.push(`${label} has an unknown field "${key}"`);
      const file = isText ? block.text : block.image;
      if (seen.has(file)) errors.push(`${label} repeats ${file}`);
      seen.add(file);
      const problem = safeRelative(dir, file);

      if (isText) {
        if (lastWasText) warnings.push(`${label} follows another text block; they read as one text, so consider one file`);
        lastWasText = true;
        if (typeof file !== 'string' || !TEXT_EXTENSIONS.includes(path.extname(file).toLowerCase())) return errors.push(`${label} text "${file}" must be a .txt or .md file`);
        // Only these names are kept out of the deployment by .vercelignore.
        if (!TEXT_NAME.test(file)) return errors.push(`${label} text "${file}" must be named body.txt, body.md, body-2.md, … so it is never deployed`);
        if (problem) return errors.push(`${label} text "${file}" ${problem}`);
        const read = readText(path.join(dir, file));
        if (read.error) return errors.push(`${label} text "${file}" ${read.error}`);
        if (!read.text.trim()) return errors.push(`${label} text "${file}" is empty`);
        const t = { type: 'text', file, kind: path.extname(file).toLowerCase() === '.md' ? 'md' : 'txt', text: read.text };
        result.blocks.push(t); result.texts.push(t);
        return;
      }

      lastWasText = false;
      if (typeof block.alt !== 'string' || !block.alt.trim()) errors.push(`${label} (${file}) has no alt text; describe what the image shows`);
      else {
        if (/[\r\n]/.test(block.alt)) errors.push(`${label} alt text must be a single line`);
        if ([...block.alt].length > LIMITS.alt) errors.push(`${label} alt text is longer than ${LIMITS.alt} characters`);
      }
      if (block.caption !== undefined && block.caption !== null) {
        if (typeof block.caption !== 'string' || !block.caption.trim()) errors.push(`${label} caption is empty; remove the field instead`);
        else if ([...block.caption].length > LIMITS.caption) errors.push(`${label} caption is longer than ${LIMITS.caption} characters`);
      }
      if (typeof file !== 'string' || !file.startsWith('images/')) return errors.push(`${label} image "${file}" must be in images/`);
      if (problem) return errors.push(`${label} image "${file}" ${problem}`);
      const ext = path.extname(file).toLowerCase();
      if (!IMAGE_EXTENSIONS.includes(ext)) return errors.push(`${label} ${file}: unsupported format "${ext}"; use JPEG, PNG, or WebP`);
      const buf = fs.readFileSync(path.join(dir, file));
      const probe = probeImage(buf);
      if (probe.error) return errors.push(`${label} ${file} ${probe.error}`);
      if (!SUPPORTED[probe.format].includes(ext)) errors.push(`${label} ${file} is ${probe.format.toUpperCase()} but is named ${ext}`);
      if (probe.metadata.length) {
        errors.push(`${label} ${file} still carries metadata (${probe.metadata.join(', ')}); strip it before publishing: ` +
          `exiftool -all= -tagsfromfile @ -ICC_Profile -Orientation -overwrite_original ${path.relative(root, path.join(dir, file))}`);
      }
      if (buf.length > IMAGE_MAX_BYTES) errors.push(`${label} ${file} is larger than ${IMAGE_MAX_BYTES / 1e6} MB`);
      else if (buf.length > IMAGE_WARN_BYTES) warnings.push(`${label} ${file} is ${(buf.length / 1e6).toFixed(1)} MB; consider a long edge of 2,400–3,000 px`);
      const im = {
        type: 'image', file, alt: typeof block.alt === 'string' ? block.alt : '', caption: block.caption ?? null,
        width: probe.width, height: probe.height, format: probe.format, bytes: buf.length,
      };
      result.blocks.push(im); result.images.push(im);
    });
    const length = result.texts.reduce((n, t) => n + [...t.text].length, 0);
    if (length > LIMITS.body) warnings.push(`the text is longer than ${LIMITS.body} characters, the form's limit`);
  }

  // Everything in a published directory is deployed, so nothing may sit there
  // that the record does not name.
  const known = new Set([RECORD_FILE, GENERATED_FILE, ...seen].filter((f) => typeof f === 'string'));
  for (const file of walk(dir)) {
    if (known.has(file)) continue;
    const msg = `${file} is in the directory but not in the record`;
    if (where === 'published') errors.push(`${msg}; it would be deployed. Remove it or add it to blocks`);
    else warnings.push(msg);
  }

  // Things the publication checklist asks to look for by hand.
  const said = [...result.texts.map((t) => t.text), record.title, record.author, record.context,
    ...result.images.flatMap((im) => [im.alt, im.caption])]
    .filter((s) => typeof s === 'string').join('\n');
  if (EMAIL_LIKE.test(said)) warnings.push('something that looks like an email address appears in the material; confirm the sender meant it to be published');
  if (REFERENCE_LIKE.test(said)) warnings.push('something that looks like a mailbox reference (O–…) appears in the material');

  return result;
}

function walk(dir, prefix = '') {
  const out = [];
  for (const e of fs.readdirSync(path.join(dir, prefix), { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${e.name}` : e.name;
    if (e.name === '.DS_Store') continue;
    if (e.isDirectory()) out.push(...walk(dir, rel));
    else out.push(rel);
  }
  return out.sort();
}

// Every record in the repository, with the duplicates between drafts and
// published marked on both.
function inspectAll(root, opts) {
  const d = dirs(root);
  const pub = listSlugs(d.published);
  const draft = listSlugs(d.drafts);
  const results = [
    ...pub.map((s) => inspect(root, s, 'published', opts)),
    ...draft.map((s) => inspect(root, s, 'draft', opts)),
  ];
  for (const r of results) {
    if (pub.includes(r.slug) && draft.includes(r.slug)) {
      r.errors.push(`the slug "${r.slug}" exists both as a draft and as a published Observation`);
    }
  }
  return results;
}

// Published records in reading order: earliest first, then by slug, so the
// order never depends on the file system.
function publishedInOrder(root, opts) {
  const results = listSlugs(dirs(root).published).map((s) => inspect(root, s, 'published', opts));
  const bad = results.filter((r) => r.errors.length);
  if (bad.length) {
    const lines = bad.flatMap((r) => r.errors.map((e) => `  ${r.slug}: ${e}`));
    const err = new Error(`published Observations have errors:\n${lines.join('\n')}`);
    err.results = bad;
    throw err;
  }
  return sortRecords(results);
}

function sortRecords(results) {
  return results.slice().sort((a, b) =>
    parsePublishedAt(a.record.published_at) - parsePublishedAt(b.record.published_at) ||
    (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0));
}

module.exports = {
  PUBLISHED_DIR, DRAFTS_DIR, RECORD_FILE, GENERATED_FILE, LIMITS, IMAGE_EXTENSIONS, TEXT_EXTENSIONS,
  isSlug, parsePublishedAt, dirs, listSlugs, locate, recordDir, safeRelative, readText,
  inspect, inspectAll, publishedInOrder, sortRecords,
};
